version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: EchoMind.Service/Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: EchoMind.Web
      dockerfile: Dockerfile
    ports:
      - "80:80"
