# Generated by Django 5.2.4 on 2025-09-26 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('filename', models.FileField(upload_to='audio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('localpath', models.CharField(blank=True, max_length=512, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
