# Generated by Django 5.2.6 on 2025-09-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='filename',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
